### ISSUE TITLE
Integration with pandas

### ISSUE THREAD

**Issue by webermarcolivier** [Yoyoyoyoyoyoyo/XlsxFormatter#1]
Hi,

Do you know if this could be used with the pandas implementation of xlsx writer?

Thanks,

Marc

**Comment by Yoyoyoyoyoyoyo** [comment]
I've never used Xlsxwriter with pandas, so I'm not sure. It comes down to whether or not you can create your workbook using the Book class provided here, or whether you're forced to use Xlsxwriter's Workbook class. 

I almost always use pandas to gather and organize my data, and I guess I haven't known what pandas' ExcelWriter would do for me except get me out of a loop or two when printing data. I may look into this later to see what I'm missing out on.

**Comment by webermarcolivier** [comment]
Indeed I use a lot the xlsxwriter with pandas, for example at the end of an analysis to present some results with enhanced formatting such as colormap background. I wrote a small quick-and-dirty workaround wrapper inspired by your code, [xlsxpandasformatter](https://github.com/webermarcolivier/xlsxpandasformatter).
