### ISSUE TITLE
Simple sheet initialization failure

### ISSUE THREAD

**Issue by nesretep** [Yoyoyoyoyoyoyo/XlsxFormatter#2]
In trying to create a simple Book object with one Sheet, I get:
`Traceback (most recent call last):
  File "forms2.py", line 7, in <module>
    sheet = book.add_book_sheet("Requisition Form")
  File "/home/nesretep/git/formstest/format_classes.py", line 124, in add_book_sheet
    'optimization': self.optimization,
AttributeError: 'Book' object has no attribute 'optimization'
`

If I comment out the offending line in format_classes.py, I get a new error:
`Traceback (most recent call last):
  File "forms2.py", line 7, in <module>
    sheet = book.add_book_sheet("Requisition Form")
  File "/home/nesretep/git/formstest/format_classes.py", line 138, in add_book_sheet
    worksheet._initialize(init_data)
  File "/home/nesretep/.local/lib/python3.5/site-packages/xlsxwriter/worksheet.py", line 3443, in _initialize
    self.constant_memory = init_data['constant_memory']
KeyError: 'constant_memory'
Exception ignored in: <bound method Workbook.__del__ of <format_classes.Book object at 0x7f562d748898>>
Traceback (most recent call last):
  File "/home/nesretep/.local/lib/python3.5/site-packages/xlsxwriter/workbook.py", line 153, in __del__
    raise Exception("Exception caught in workbook destructor. "
Exception: Exception caught in workbook destructor. Explicit close() may be required for workbook.
`

My python code look is _extremely simple_ and shouldn't fail this badly:
`#! /usr/bin/env python3

import xlsxwriter
import format_classes

book = format_classes.Book("testform2.xlsx")
sheet = book.add_book_sheet("Requisition Form")
sheet.box(3, 1, 12, 5)
book.close()`

**Comment by Yoyoyoyoyoyoyo** [comment]
I just ran your code locally and it worked fine. What versions of Python and Xlsxwriter are you using? I just used Python 3.5.2 and 0.9.3 for Xlsxwriter.

**Comment by nesretep** [comment]
I am using python 3.5.2 and xlsxwriter 1.0.2 (installed using pip).

**Comment by Yoyoyoyoyoyoyo** [comment]
I updated in an env and got your error message, so an update in xlsxwriter broke my stuff. I'll give it a look in the next couple days and see what I can find.

**Comment by Yoyoyoyoyoyoyo** [comment]
All it needed was a dictionary updated. I pushed the fix. Now it'll work with the new version of XlsxWriter, but won't work with older versions.

**Comment by nesretep** [comment]
Does the worksheet.write_rich_string() method from xlsxwriter work with your Sheet class?
